version: '3'
services:
  editor-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: editor-server # 依赖于当前 Dockerfile 创建镜像
    container_name: editor-server
    ports:
      - 8081:3000 # 宿主机通过 8081 访问